//
// Created by Alex Cohn on 12/07/2017.
//

#ifndef NATIVE_CAMERA2_CAMERA_METADATA_H
#define NATIVE_CAMERA2_CAMERA_METADATA_H

#include_next "system/camera_metadata.h"

//enum camera_metadata_enum_android_request_available_capabilities_6_0_0_r1 {
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING = ANDROID_REQUEST_AVAILABLE_CAPABILITIES_ZSL,
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS,
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE,
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING,
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT,
//    ANDROID_REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO,
//};

enum camera_metadata_tag_6_0_0_r1 {
//    ANDROID_DEPTH = ANDROID_SECTION_COUNT + 1,
//    ANDROID_DEPTH_START            = ANDROID_DEPTH             << 16,
//
//    ANDROID_DEPTH_MAX_DEPTH_SAMPLES =                 // int32        | system
//    ANDROID_DEPTH_START,
//    ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS,
    ANDROID_SENSOR_OPAQUE_RAW_SIZE = ANDROID_SENSOR_END + 1,
};


#endif //NATIVE_CAMERA2_CAMERA_METADATA_H
